# Task-6 (Numpy)   syed mishal oct 

In [1]:
import numpy as np

In [2]:
A = input('Enter space-separated numbers : ').strip().split(' ')
A = np.array(A)
Reversed_A = A[::-1]
print(Reversed_A)

Enter space-separated numbers : 2 3 4 5
['5' '4' '3' '2']


# Shape and Reshape

In [7]:
A = np.array(input('Enter space-separated numbers : ').split(),int)
print(A.shape)
A = A.reshape(3,3)
print(A)

Enter space-separated numbers : 2
(1,)


ValueError: cannot reshape array of size 1 into shape (3,3)

# transpose and flatten

In [8]:
# N Rows and M Columns
N,M = map(int, input('Enter space-separeted values of N and M : ').split())
A = np.array([input('Enter space-separated elements : ').split() for _ in range(N)],int) # Enter elements for each row. 
print(A.transpose())
print(A.flatten())


Enter space-separeted values of N and M : 2 3
Enter space-separated elements : 2 3 4 5 6 
Enter space-separated elements : 4 567 7 8 9
[[  2   4]
 [  3 567]
 [  4   7]
 [  5   8]
 [  6   9]]
[  2   3   4   5   6   4 567   7   8   9]


# Concatenate

In [9]:
P,N,M = map(int, input('Enter space-separeted values of N and M and P : ').split())
A = np.array([input('Enter space-separated elements : ').split() for _ in range(P)],int)
B = np.array([input('Enter space-separated elements : ').split() for _ in range(N)],int)
C = np.concatenate((A,B),axis = 0)
print(C)

Enter space-separeted values of N and M and P : 3 3 1
Enter space-separated elements : 2 34 5 6
Enter space-separated elements : 3 45 2 3
Enter space-separated elements : 3 6 7


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

# Zeros and Ones



In [10]:
A = tuple(map(int, input('Enter space-separeted values of X and Y and Z : ').split()))
print(np.zeros(A, int))
print(np.ones(A, int))

Enter space-separeted values of X and Y and Z : 2 3 4
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


# Eye and Identity

In [12]:
N,M = map(int, input('Enter space-separeted values of N and M : ').split())
print(np.eye(N,M))

Enter space-separeted values of N and M : 3 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# array mathematics

In [13]:
N,M = map(int, input('Enter space-separeted values of M and N : ').split()) # N lines and M integer/line
A = np.array([list(map(int, input('Enter space-separated elements : ').split())) for n in range(N)])
B = np.array([list(map(int, input('Enter space-separated elements : ').split())) for n in range(N)])

print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.divide(A,B))
print(np.mod(A,B))
print(np.power(A,B))

Enter space-separeted values of M and N : 5 6
Enter space-separated elements : 5 6 7 
Enter space-separated elements : 76 5 6
Enter space-separated elements : 5 6 7
Enter space-separated elements : 5 67 8
Enter space-separated elements : 6 7 8
Enter space-separated elements : 5 67 8
Enter space-separated elements : 5 6 876
Enter space-separated elements : 5 6 7
Enter space-separated elements : 6 7 8
Enter space-separated elements : 5 6 8
[[ 10  73  15]
 [ 81  11 882]
 [ 10  12  14]
 [ 11  74  16]
 [ 11  13  16]]
[[   0  -61   -1]
 [  71   -1 -870]
 [   0    0    0]
 [  -1   60    0]
 [   1    1    0]]
[[  25  402   56]
 [ 380   30 5256]
 [  25   36   49]
 [  30  469   64]
 [  30   42   64]]
[[1.00000000e+00 8.95522388e-02 8.75000000e-01]
 [1.52000000e+01 8.33333333e-01 6.84931507e-03]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [8.33333333e-01 9.57142857e+00 1.00000000e+00]
 [1.20000000e+00 1.16666667e+00 1.00000000e+00]]
[[0 6 7]
 [1 5 6]
 [0 0 0]
 [5 4 0]
 [1 1 0]]
[[       3125

# floor ,ceil,reint

In [14]:
A = np.array([list(map(float, input('Enter space-separated elements : ').split()))])
print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))

Enter space-separated elements : 2.3 4 5.6 4 5.4
[[2. 4. 5. 4. 5.]]
[[3. 4. 6. 4. 6.]]
[[2. 4. 6. 4. 5.]]


# sum and product numpy

In [ ]:
N, M = map(int, input('Enter space-separated values of N and M : ').split()) # N lines and M integers/line
A = np.array([input('Enter your numbers : ').split() for _ in range(N)], int)
Sum = np.sum(A,axis = 0)
Prod = np.prod(Sum,axis = 0)
print(Prod)

# min and max

In [ ]:
N, M = map(int, input('Enter space-separated values of N and M : ').split())
A = np.array([input('Enter your numbers : ').split() for _ in range(N)], int)
Min = np.min(A,axis = 1)
print(np.max(Min))

# Mean, Var and Std

In [ ]:
N, M = map(int, input('Enter space-separated values of N and M : ').split())
A = np.array([input('Enter your numbers : ').split() for _ in range(N)], int)
print(np.mean(A,axis = 1))
print(np.var(A,axis = 0))
np.set_printoptions(legacy='1.13')
print(np.std(A))

# dot and cross

In [ ]:
N = int(input('Enter space-separeted values of N : ')) # N lines and M integer/line
A = np.array([input('Enter your numbers : ').split() for _ in range(N)], int)
B = np.array([input('Enter your numbers : ').split() for _ in range(N)], int)
print(np.dot(A,B))

# polynomials

In [ ]:
A,B,C = map(float, input('Enter space-separated values of Coefficients : ').split())
X = int(input('Enter value of X  : ')) 
print(np.polyval([A,B,C],X))

# linear algebra

In [ ]:
N = int(input('Enter value of N  : ')) 
A = np.array([input('Enter your numbers : ').split() for _ in range(N)],float)
# Output needs to be round to 2 decimal points
print(round(np.linalg.det(A),2))